-- 25-10-14
 CREATE TABLE `tb_code_group` (
   `group_code` varchar(50) NOT NULL COMMENT '코드 그룹 ID (PK)',
   `group_name` varchar(100) NOT NULL COMMENT '코드 그룹명 (유일)',
   `description` varchar(255) DEFAULT NULL COMMENT '그룹에 대한 상세 설명',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`group_code`),
   UNIQUE KEY `uk_code_group_name` (`group_name`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='코드 그룹 마스터: 시스템 공통 코드의 상위 그룹을 정의하는 테이블. 대표 조인: tb_code.';

 CREATE TABLE `tb_code` (
   `code_id` bigint NOT NULL AUTO_INCREMENT COMMENT '코드 ID (PK, 서로게이트 키)',
   `group_code` varchar(50) NOT NULL COMMENT '코드 그룹 ID (FK)',
   `code` varchar(50) NOT NULL COMMENT '코드 값 (그룹 내 유일)',
   `name` varchar(100) NOT NULL COMMENT '코드 명칭',
   `description` varchar(255) DEFAULT NULL COMMENT '코드에 대한 상세 설명',
   `use_yn` char(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부 (Y/N)',
   `sort_order` int DEFAULT NULL COMMENT '정렬 순서',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`code_id`),
   UNIQUE KEY `uk_code_group_code` (`group_code`,`code`),
   KEY `idx_code_group_sort` (`group_code`,`sort_order`),
   CONSTRAINT `fk_code_group_code` FOREIGN KEY (`group_code`) REFERENCES `tb_code_group` (`group_code`) ON DELETE RESTRICT,
   CONSTRAINT `ck_code_use_yn` CHECK ((`use_yn` in (_utf8mb4'Y',_utf8mb4'N')))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='코드 마스터: 그룹에 종속된 개별 코드를 정의하는 테이블. 대표 조인: tb_equipment.status_code_id, tb_work_order.status_code_id 등.';
 
CREATE TABLE `tb_shift` (
   `shift_id` bigint NOT NULL AUTO_INCREMENT COMMENT '교대 ID (PK)',
   `shift_code` varchar(10) NOT NULL COMMENT '교대 코드 (유일, 예: A, B, C)',
   `shift_name` varchar(50) NOT NULL COMMENT '교대 명칭 (예: 주간조)',
   `start_time` time NOT NULL COMMENT '교대 시작 시간',
   `end_time` time NOT NULL COMMENT '교대 종료 시간',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`shift_id`),
   UNIQUE KEY `uk_shift_code` (`shift_code`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='교대 마스터: 교대 근무의 기본 정보(코드, 시간 등)를 정의하는 테이블.';

CREATE TABLE `tb_workshop` (
   `workshop_id` varchar(36) NOT NULL COMMENT '작업장 그룹 ID (PK, UUID)',
   `workshop_name` varchar(255) NOT NULL COMMENT '작업장 그룹명 (유일)',
   `description` varchar(255) DEFAULT NULL COMMENT '설명',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`workshop_id`),
   UNIQUE KEY `uk_workshop_name` (`workshop_name`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='작업장 그룹 마스터: 생산 라인의 상위 그룹을 정의하는 테이블. 대표 조인: tb_workcenter.';


CREATE TABLE `tb_workcenter` (
   `workcenter_id` varchar(36) NOT NULL COMMENT '작업장 ID (PK, UUID)',
   `workcenter_name` varchar(255) NOT NULL COMMENT '작업장명 (유일)',
   `workshop_id` varchar(36) NOT NULL COMMENT '작업장 그룹 ID (FK)',
   `description` varchar(255) DEFAULT NULL COMMENT '설명',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`workcenter_id`),
   UNIQUE KEY `uk_workcenter_name` (`workcenter_name`),
   KEY `idx_workcenter_workshop_id` (`workshop_id`),
   CONSTRAINT `fk_workcenter_workshop` FOREIGN KEY (`workshop_id`) REFERENCES `tb_workshop` (`workshop_id`) ON DELETE RESTRICT
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='작업장 마스터: 설비 및 공정의 상위 그룹. 대표 조인: tb_equipment, tb_shift_calendar.';


CREATE TABLE `tb_process` (
   `process_id` varchar(36) NOT NULL COMMENT '공정 ID (PK, UUID)',
   `process_name` varchar(255) NOT NULL COMMENT '공정명 (유일)',
   `description` varchar(255) DEFAULT NULL COMMENT '설명',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`process_id`),
   UNIQUE KEY `uk_process_name` (`process_name`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='공정 마스터: 생산 라우팅의 작업 단계를 정의하는 테이블. 대표 조인: tb_equipment, tb_work_order, tb_production_performance.';

 CREATE TABLE `tb_equipment` (
   `equipment_id` varchar(36) NOT NULL COMMENT '설비 ID (PK, UUID)',
   `equipment_name` varchar(255) NOT NULL COMMENT '설비명 (유일)',
   `workcenter_id` varchar(36) NOT NULL COMMENT '작업장 ID (FK)',
   `process_id` varchar(36) NOT NULL COMMENT '공정 ID (FK)',
   `status_code_id` bigint NOT NULL COMMENT '설비 상태 코드 ID (FK→tb_code)',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`equipment_id`),
   UNIQUE KEY `uk_equipment_name` (`equipment_name`),
   KEY `idx_equipment_workcenter_id` (`workcenter_id`),
   KEY `idx_equipment_process_id` (`process_id`),
   KEY `idx_equipment_status_code_id` (`status_code_id`),
   KEY `idx_equipment_proc_wc` (`process_id`,`workcenter_id`),
   CONSTRAINT `fk_eqp_proc` FOREIGN KEY (`process_id`) REFERENCES `tb_process` (`process_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_eqp_status` FOREIGN KEY (`status_code_id`) REFERENCES `tb_code` (`code_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_eqp_wc` FOREIGN KEY (`workcenter_id`) REFERENCES `tb_workcenter` (`workcenter_id`) ON DELETE RESTRICT
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='설비 마스터: 실적/상태로그/작업지시/교대달력과 결합되는 핵심 마스터(UTC).';

CREATE TABLE `tb_shift_calendar` (
   `calendar_id` bigint NOT NULL AUTO_INCREMENT COMMENT '교대 달력 ID (PK)',
   `shift_date` date NOT NULL COMMENT '근무 날짜',
   `shift_id` bigint NOT NULL COMMENT '교대 ID (FK)',
   `equipment_id` varchar(36) DEFAULT NULL COMMENT '설비 ID (FK) - 선택',
   `workcenter_id` varchar(36) DEFAULT NULL COMMENT '작업장 ID (FK) - 선택',
   `start_ts` datetime NOT NULL COMMENT '교대 시작 (UTC)',
   `end_ts` datetime NOT NULL COMMENT '교대 종료 (UTC)',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`calendar_id`),
   UNIQUE KEY `uk_shiftcal_all` (`shift_date`,`shift_id`,`equipment_id`, `workcenter_id`),
   KEY `idx_shiftcal_date_shift_eqp` (`shift_date`,`shift_id`,`equipment_id`),
   KEY `idx_shiftcal_date_shift_wc` (`shift_date`,`shift_id`,`workcenter_id`),
   KEY `fk_shiftcal_shift` (`shift_id`),
   KEY `fk_shiftcal_eqp` (`equipment_id`),
   KEY `fk_shiftcal_wc` (`workcenter_id`),
   CONSTRAINT `fk_shiftcal_eqp` FOREIGN KEY (`equipment_id`) REFERENCES `tb_equipment` (`equipment_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_shiftcal_shift` FOREIGN KEY (`shift_id`) REFERENCES `tb_shift` (`shift_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_shiftcal_wc` FOREIGN KEY (`workcenter_id`) REFERENCES `tb_workcenter` (`workcenter_id`) ON DELETE RESTRICT,
   CONSTRAINT `ck_shiftcal_time_order` CHECK ((`end_ts` > `start_ts`))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='교대 달력: 날짜/교대 × (설비 또는 작업장) 단위의 집계 프레임(UTC). XOR+부분 유니크로 중복 차단.';

CREATE TABLE `tb_role` (
   `role_id` bigint NOT NULL AUTO_INCREMENT COMMENT '역할 ID (PK)',
   `role_code` varchar(50) NOT NULL COMMENT '역할 코드 (전역 유일) 예: ROLE_OP, ROLE_QA, ROLE_ADMIN',
   `role_name` varchar(100) NOT NULL COMMENT '역할 명칭',
   `description` varchar(255) DEFAULT NULL COMMENT '설명',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`role_id`),
   UNIQUE KEY `uk_role_code` (`role_code`),
   CONSTRAINT `ck_role_is_deleted` CHECK ((`is_deleted` in (0,1)))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='역할 마스터: 인가 레벨 정의. ROLE_OP/QA/ADMIN 기본 시드 권장(UTC).';

CREATE TABLE `tb_user` (
   `user_id` varchar(36) NOT NULL COMMENT '사용자 ID (UUID, PK)',
   `username` varchar(50) NOT NULL COMMENT '로그인 ID (유일, 소문자 권장)',
   `email` varchar(255) DEFAULT NULL COMMENT '이메일(선택, 유일 권장)',
   `password_hash` varchar(100) NOT NULL COMMENT '비밀번호 해시(예: BCrypt 60자, Argon2id 가능)',
   `password_algo` varchar(20) NOT NULL DEFAULT 'bcrypt' COMMENT '해시 알고리즘(bcrypt/argon2id)',
   `is_active` tinyint NOT NULL DEFAULT '1' COMMENT '활성 여부(1/0)',
   `failed_login_count` int NOT NULL DEFAULT '0' COMMENT '연속 실패 횟수(>=0)',
   `locked_until` datetime DEFAULT NULL COMMENT '잠금 해제 예정 시각(UTC)',
   `last_login_at` datetime DEFAULT NULL COMMENT '마지막 로그인 시각(UTC)',
   `phone` varchar(30) DEFAULT NULL COMMENT '연락처(선택)',
   `display_name` varchar(100) DEFAULT NULL COMMENT '표시명(선택)',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`user_id`),
   UNIQUE KEY `uk_user_username` (`username`),
   UNIQUE KEY `uk_user_email` (`email`),
   CONSTRAINT `ck_user_failed_cnt` CHECK ((`failed_login_count` >= 0)),
   CONSTRAINT `ck_user_is_active` CHECK ((`is_active` in (0,1))),
   CONSTRAINT `ck_user_is_deleted` CHECK ((`is_deleted` in (0,1)))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자 마스터: 로그인/상태/보안 메타. 해시는 필수, 평문 금지(UTC).';

CREATE TABLE `tb_user_role` (
   `user_role_id` bigint NOT NULL AUTO_INCREMENT COMMENT '사용자-역할 매핑 ID (PK)',
   `user_id` varchar(36) NOT NULL COMMENT '사용자 ID (FK)',
   `role_id` bigint NOT NULL COMMENT '역할 ID (FK)',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그(0/1)',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`user_role_id`),
   UNIQUE KEY `uk_user_role` (`user_id`,`role_id`),
   KEY `idx_userrole_user` (`user_id`),
   KEY `idx_userrole_role` (`role_id`),
   CONSTRAINT `fk_userrole_role` FOREIGN KEY (`role_id`) REFERENCES `tb_role` (`role_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_userrole_user` FOREIGN KEY (`user_id`) REFERENCES `tb_user` (`user_id`) ON DELETE RESTRICT,
   CONSTRAINT `ck_userrole_is_deleted` CHECK ((`is_deleted` in (0,1)))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자-역할 매핑(보수형): FK 삭제 RESTRICT, 중복 배정 방지(UTC).';

CREATE TABLE `tb_menu` (
   `menu_id` bigint NOT NULL AUTO_INCREMENT COMMENT '메뉴 ID (PK)',
   `parent_id` bigint DEFAULT NULL COMMENT '부모 메뉴 ID (Self FK, 최상위 NULL)',
   `menu_code` varchar(100) NOT NULL COMMENT '메뉴 코드(전역 유일) 예: DASHBOARD, PROD_RESULT',
   `menu_name` varchar(150) NOT NULL COMMENT '메뉴 표시명',
   `path` varchar(255) NOT NULL COMMENT '라우트/URL 경로 예: /dashboard',
   `component` varchar(255) DEFAULT NULL COMMENT '프론트 컴포넌트 키(선택)',
   `icon` varchar(100) DEFAULT NULL COMMENT '아이콘 키(선택)',
   `sort_order` int NOT NULL DEFAULT '0' COMMENT '정렬 순서',
   `is_public` tinyint NOT NULL DEFAULT '0' COMMENT '비로그인 접근(0/1)',
   `is_active` tinyint NOT NULL DEFAULT '1' COMMENT '활성(0/1)',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제(0/1)',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`menu_id`),
   UNIQUE KEY `uk_menu_code` (`menu_code`),
   KEY `idx_menu_parent` (`parent_id`),
   KEY `idx_menu_path` (`path`),
   KEY `idx_menu_sort` (`sort_order`),
   KEY `idx_menu_parent_sort` (`parent_id`,`sort_order`),
   CONSTRAINT `fk_menu_parent` FOREIGN KEY (`parent_id`) REFERENCES `tb_menu` (`menu_id`) ON DELETE RESTRICT,
   CONSTRAINT `ck_menu_flags` CHECK (((`is_public` in (0,1)) and (`is_active` in (0,1)) and (`is_deleted` in (0,1))))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='메뉴 마스터(보수형): 부모 삭제 전 자식 정리 필요, 트리/정렬 인덱스 강화(UTC).';

CREATE TABLE `tb_role_menu` (
   `role_menu_id` bigint NOT NULL AUTO_INCREMENT COMMENT '역할-메뉴 매핑 ID (PK)',
   `role_id` bigint NOT NULL COMMENT '역할 ID (FK)',
   `menu_id` bigint NOT NULL COMMENT '메뉴 ID (FK)',
   `allow_read` tinyint NOT NULL DEFAULT '1' COMMENT '읽기 허용(0/1)',
   `allow_write` tinyint NOT NULL DEFAULT '0' COMMENT '쓰기 허용(0/1)',
   `allow_exec` tinyint NOT NULL DEFAULT '0' COMMENT '실행 허용(0/1)',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제(0/1)',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`role_menu_id`),
   UNIQUE KEY `uk_role_menu` (`role_id`,`menu_id`),
   KEY `idx_rm_role` (`role_id`),
   KEY `idx_rm_menu` (`menu_id`),
   CONSTRAINT `fk_rm_menu` FOREIGN KEY (`menu_id`) REFERENCES `tb_menu` (`menu_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_rm_role` FOREIGN KEY (`role_id`) REFERENCES `tb_role` (`role_id`) ON DELETE RESTRICT,
   CONSTRAINT `ck_rm_flags` CHECK (((`allow_read` in (0,1)) and (`allow_write` in (0,1)) and (`allow_exec` in (0,1)) and (`is_deleted` in (0,1))))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='역할-메뉴 매핑(보수형): FK 삭제 RESTRICT, 플래그 무결성(UTC).';

CREATE TABLE `tb_shift_assignment` (
   `assignment_id` bigint NOT NULL AUTO_INCREMENT COMMENT '배치 ID (PK)',
   `shift_date` date NOT NULL COMMENT '근무 날짜',
   `shift_id` bigint NOT NULL COMMENT '교대 ID (FK)',
   `worker_id` varchar(36) NOT NULL COMMENT '작업자 ID (FK→tb_user.user_id)',
   `equipment_id` varchar(36) DEFAULT NULL COMMENT '설비 배치 시 사용',
   `workcenter_id` varchar(36) DEFAULT NULL COMMENT '작업장 배치 시 사용',
   `start_ts` datetime NOT NULL COMMENT '배치 시작 (UTC)',
   `end_ts` datetime NOT NULL COMMENT '배치 종료 (UTC)',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`assignment_id`),
   UNIQUE KEY `uk_assign_eqp` (`shift_date`,`shift_id`,`worker_id`,`equipment_id`),
   UNIQUE KEY `uk_assign_wc` (`shift_date`,`shift_id`,`worker_id`,`workcenter_id`),
   KEY `idx_assign_shift_worker` (`shift_date`,`shift_id`,`worker_id`),
   KEY `idx_assign_worker` (`worker_id`),
   KEY `idx_assign_eqp` (`equipment_id`),
   KEY `idx_assign_wc` (`workcenter_id`),
   KEY `fk_assign_shift` (`shift_id`),
   CONSTRAINT `fk_assign_eqp` FOREIGN KEY (`equipment_id`) REFERENCES `tb_equipment` (`equipment_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_assign_shift` FOREIGN KEY (`shift_id`) REFERENCES `tb_shift` (`shift_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_assign_user` FOREIGN KEY (`worker_id`) REFERENCES `tb_user` (`user_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_assign_wc` FOREIGN KEY (`workcenter_id`) REFERENCES `tb_workcenter` (`workcenter_id`) ON DELETE RESTRICT,
   CONSTRAINT `ck_assign_time_order` CHECK ((`end_ts` > `start_ts`))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='교대 배치: 날짜/교대/작업자 × (설비 또는 작업장) 다건 배정(UTC). XOR+부분 유니크, 작업자=tb_user FK.';

 CREATE TABLE `tb_item` (
   `item_id` varchar(36) NOT NULL COMMENT '품목 ID (PK, UUID)',
   `item_code` varchar(50) NOT NULL COMMENT '품목 코드 (유일)',
   `item_name` varchar(255) NOT NULL COMMENT '품목명',
   `item_type` char(1) NOT NULL COMMENT '품목 유형 (R:원자재, P:반제품, F:완제품)',
   `unit` varchar(10) NOT NULL COMMENT '단위 (예: EA, KG)',
   `description` varchar(255) DEFAULT NULL COMMENT '설명',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`item_id`),
   UNIQUE KEY `uk_item_code` (`item_code`),
   KEY `idx_item_name` (`item_name`),
   CONSTRAINT `ck_item_type` CHECK ((`item_type` in (_utf8mb4'R',_utf8mb4'P',_utf8mb4'F')))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='품목 마스터: 생산/재고 관리 대상. 대표 조인: tb_work_order, tb_bom, tb_material_lot.';

CREATE TABLE `tb_warehouse` (
   `warehouse_id` varchar(36) NOT NULL COMMENT '창고 ID (PK, UUID)',
   `warehouse_name` varchar(255) NOT NULL COMMENT '창고명 (유일)',
   `location` varchar(255) DEFAULT NULL COMMENT '위치 정보',
   `description` varchar(255) DEFAULT NULL COMMENT '설명',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`warehouse_id`),
   UNIQUE KEY `uk_warehouse_name` (`warehouse_name`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='창고 마스터: 자재 및 제품의 보관 장소를 정의하는 테이블. 대표 조인: tb_material_lot.';

CREATE TABLE `tb_production_plan` (
   `plan_id` varchar(36) NOT NULL COMMENT '생산 계획 ID (PK, UUID)',
   `plan_number` varchar(50) NOT NULL COMMENT '계획 번호 (유일)',
   `item_id` varchar(36) NOT NULL COMMENT '계획 품목 ID (FK)',
   `target_qty` decimal(10,4) NOT NULL COMMENT '계획 수량',
   `start_date` date NOT NULL COMMENT '계획 시작일',
   `end_date` date NOT NULL COMMENT '계획 종료일',
   `status` char(1) NOT NULL COMMENT '계획 상태 (P:Planned, R:Released, C:Completed)',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`plan_id`),
   UNIQUE KEY `uk_plan_number` (`plan_number`),
   KEY `idx_plan_item_id` (`item_id`),
   KEY `idx_plan_start_date` (`start_date`),
   CONSTRAINT `fk_plan_item` FOREIGN KEY (`item_id`) REFERENCES `tb_item` (`item_id`) ON DELETE RESTRICT,
   CONSTRAINT `ck_plan_dates` CHECK ((`end_date` >= `start_date`)),
   CONSTRAINT `ck_plan_qty_nonneg` CHECK ((`target_qty` >= 0)),
   CONSTRAINT `ck_plan_status` CHECK ((`status` in (_utf8mb4'P',_utf8mb4'R',_utf8mb4'C')))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='생산 계획: 목표/기간/상태 무결성 보장. 대표 조인: tb_work_order.';

CREATE TABLE `tb_work_order` (
   `work_order_id` varchar(36) NOT NULL COMMENT '작업 지시 ID (PK, UUID)',
   `plan_id` varchar(36) DEFAULT NULL COMMENT '생산 계획 ID (FK) - 선택',
   `work_order_number` varchar(50) NOT NULL COMMENT '작업 지시 번호 (유일)',
   `item_id` varchar(36) NOT NULL COMMENT '생산 품목 ID (FK)',
   `process_id` varchar(36) NOT NULL COMMENT '지시 공정 ID (FK)',
   `equipment_id` varchar(36) NOT NULL COMMENT '지시 설비 ID (FK)',
   `order_qty` decimal(10,4) NOT NULL COMMENT '지시 수량',
   `produced_qty` decimal(10,4) NOT NULL DEFAULT '0.0000' COMMENT '생산 완료 수량',
   `start_ts` datetime DEFAULT NULL COMMENT '지시 시작 타임스탬프 (UTC)',
   `end_ts` datetime DEFAULT NULL COMMENT '지시 종료 타임스탬프 (UTC)',
   `status_code_id` bigint NOT NULL COMMENT '작업 지시 상태 코드 ID (FK→tb_code)',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`work_order_id`),
   UNIQUE KEY `uk_wo_number` (`work_order_number`),
   KEY `idx_wo_plan_id` (`plan_id`),
   KEY `idx_wo_item_id` (`item_id`),
   KEY `idx_wo_process_id` (`process_id`),
   KEY `idx_wo_equipment_id` (`equipment_id`),
   KEY `idx_wo_status_code_id` (`status_code_id`),
   KEY `idx_wo_eqp_start` (`equipment_id`,`start_ts`),
   CONSTRAINT `fk_wo_equipment` FOREIGN KEY (`equipment_id`) REFERENCES `tb_equipment` (`equipment_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_wo_item` FOREIGN KEY (`item_id`) REFERENCES `tb_item` (`item_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_wo_plan` FOREIGN KEY (`plan_id`) REFERENCES `tb_production_plan` (`plan_id`) ON DELETE SET NULL,
   CONSTRAINT `fk_wo_process` FOREIGN KEY (`process_id`) REFERENCES `tb_process` (`process_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_wo_status_code` FOREIGN KEY (`status_code_id`) REFERENCES `tb_code` (`code_id`) ON DELETE RESTRICT,
   CONSTRAINT `ck_wo_qty_nonneg` CHECK (((`order_qty` >= 0) and (`produced_qty` >= 0))),
   CONSTRAINT `ck_wo_time_order` CHECK (((`start_ts` is null) or (`end_ts` is null) or (`end_ts` >= `start_ts`)))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='작업 지시: 실작업 단위. 시간/수량/상태 무결성 보강, 설비×시간 인덱스로 조회 최적화(UTC).';


 CREATE TABLE `tb_bom` (
   `bom_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'BOM ID (PK)',
   `parent_item_id` varchar(36) NOT NULL COMMENT '상위 품목 ID (FK)',
   `child_item_id` varchar(36) NOT NULL COMMENT '하위 품목 ID (FK)',
   `quantity` decimal(10,4) NOT NULL COMMENT '소요 수량(>0)',
   `line_no` int NOT NULL COMMENT 'BOM 라인 번호',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`bom_id`),
   UNIQUE KEY `uk_bom_line` (`parent_item_id`,`child_item_id`,`line_no`),
   KEY `idx_bom_parent_item_id` (`parent_item_id`),
   KEY `idx_bom_child_item_id` (`child_item_id`),
   CONSTRAINT `fk_bom_child` FOREIGN KEY (`child_item_id`) REFERENCES `tb_item` (`item_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_bom_parent` FOREIGN KEY (`parent_item_id`) REFERENCES `tb_item` (`item_id`) ON DELETE RESTRICT,
   CONSTRAINT `ck_bom_qty_pos` CHECK ((`quantity` > 0))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='BOM: 제품 구성. parent×child×line 유일, 수량>0 무결성(UTC).';

CREATE TABLE `tb_material_lot` (
   `material_lot_id` varchar(36) NOT NULL COMMENT '자재 LOT ID (PK, UUID)',
   `lot_number` varchar(50) NOT NULL COMMENT 'LOT 번호 (유일)',
   `item_id` varchar(36) NOT NULL COMMENT '품목 ID (FK)',
   `warehouse_id` varchar(36) NOT NULL COMMENT '현재 창고 ID (FK)',
   `quantity` decimal(10,4) NOT NULL COMMENT 'LOT 수량(>=0)',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`material_lot_id`),
   UNIQUE KEY `uk_lot_number` (`lot_number`),
   KEY `idx_material_lot_item_id` (`item_id`),
   KEY `idx_material_lot_warehouse_id` (`warehouse_id`),
   KEY `idx_matlot_item_wh` (`item_id`,`warehouse_id`),
   CONSTRAINT `fk_material_lot_item` FOREIGN KEY (`item_id`) REFERENCES `tb_item` (`item_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_material_lot_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `tb_warehouse` (`warehouse_id`) ON DELETE RESTRICT,
   CONSTRAINT `ck_matlot_qty_nonneg` CHECK ((`quantity` >= 0))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='자재 LOT: 입고 추적 단위. 수량>=0, 품목×창고 조회 최적화(UTC).';

CREATE TABLE `tb_production_performance` (
   `performance_id` bigint NOT NULL AUTO_INCREMENT COMMENT '생산 실적 ID (PK)',
   `work_order_id` varchar(36) NOT NULL COMMENT '작업 지시 ID (FK)',
   `item_id` varchar(36) NOT NULL COMMENT '생산 품목 ID (FK)',
   `process_id` varchar(36) NOT NULL COMMENT '실적 공정 ID (FK)',
   `equipment_id` varchar(36) NOT NULL COMMENT '실적 설비 ID (FK)',
   `produced_qty` decimal(10,4) NOT NULL COMMENT '생산 수량(>=0)',
   `defect_qty` decimal(10,4) NOT NULL DEFAULT '0.0000' COMMENT '불량 수량(>=0, 생산 수량 이내)',
   `start_time` datetime NOT NULL COMMENT '작업 시작 시점 (UTC)',
   `end_time` datetime NOT NULL COMMENT '작업 종료 시점 (UTC)',
   `worker_id` varchar(36) DEFAULT NULL COMMENT '작업자 ID (FK→tb_user.user_id, 선택)',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   `request_id` varchar(64) DEFAULT NULL COMMENT 'idempotency key',
   PRIMARY KEY (`performance_id`),
   UNIQUE KEY `uk_perf_request_id` (`request_id`),
   KEY `idx_perf_wo_id` (`work_order_id`),
   KEY `idx_perf_item_id` (`item_id`),
   KEY `idx_perf_process_id` (`process_id`),
   KEY `idx_perf_equipment_id` (`equipment_id`),
   KEY `idx_perf_equipment_start_time` (`equipment_id`,`start_time`),
   KEY `idx_perf_wo_start` (`work_order_id`,`start_time`),
   KEY `idx_perf_worker` (`worker_id`),
   CONSTRAINT `fk_perf_equipment` FOREIGN KEY (`equipment_id`) REFERENCES `tb_equipment` (`equipment_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_perf_item` FOREIGN KEY (`item_id`) REFERENCES `tb_item` (`item_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_perf_process` FOREIGN KEY (`process_id`) REFERENCES `tb_process` (`process_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_perf_user` FOREIGN KEY (`worker_id`) REFERENCES `tb_user` (`user_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_perf_wo` FOREIGN KEY (`work_order_id`) REFERENCES `tb_work_order` (`work_order_id`) ON DELETE RESTRICT,
   CONSTRAINT `ck_perf_qty_nonneg` CHECK (((`produced_qty` >= 0) and (`defect_qty` >= 0))),
   CONSTRAINT `ck_perf_qty_rel` CHECK ((`defect_qty` <= `produced_qty`)),
   CONSTRAINT `ck_perf_time_order` CHECK ((`end_time` >= `start_time`))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='생산 실적: 시간/수량 무결성+설비/WO 타임라인 최적화(UTC). 작업자=tb_user FK(선택).';


 CREATE TABLE `tb_equipment_status_log` (
   `log_id` bigint NOT NULL AUTO_INCREMENT COMMENT '로그 ID (PK)',
   `equipment_id` varchar(36) NOT NULL COMMENT '설비 ID (FK)',
   `status_code_id` bigint NOT NULL COMMENT '설비 상태 코드 ID (FK→tb_code)',
   `reason_code_id` bigint DEFAULT NULL COMMENT '비가동 사유 코드 ID (FK→tb_code)',
   `work_order_id` varchar(36) DEFAULT NULL COMMENT '관련 작업 지시 ID (FK) - 선택',
   `shift_id` bigint DEFAULT NULL COMMENT '관련 교대 ID (FK) - 선택',
   `start_time` datetime NOT NULL COMMENT '상태 시작 시점 (UTC)',
   `end_time` datetime DEFAULT NULL COMMENT '상태 종료 시점 (UTC)',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`log_id`),
   KEY `idx_log_equipment_id` (`equipment_id`),
   KEY `idx_log_status_code_id` (`status_code_id`),
   KEY `idx_log_reason_code_id` (`reason_code_id`),
   KEY `idx_log_wo_id` (`work_order_id`),
   KEY `idx_log_shift_id` (`shift_id`),
   KEY `idx_log_equipment_start_time` (`equipment_id`,`start_time`),
   CONSTRAINT `fk_log_equipment` FOREIGN KEY (`equipment_id`) REFERENCES `tb_equipment` (`equipment_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_log_reason_code` FOREIGN KEY (`reason_code_id`) REFERENCES `tb_code` (`code_id`) ON DELETE SET NULL,
   CONSTRAINT `fk_log_shift` FOREIGN KEY (`shift_id`) REFERENCES `tb_shift` (`shift_id`) ON DELETE SET NULL,
   CONSTRAINT `fk_log_status_code` FOREIGN KEY (`status_code_id`) REFERENCES `tb_code` (`code_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_log_wo` FOREIGN KEY (`work_order_id`) REFERENCES `tb_work_order` (`work_order_id`) ON DELETE SET NULL,
   CONSTRAINT `ck_log_time_order` CHECK (((`end_time` is null) or (`end_time` >= `start_time`)))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='설비 상태 로그: 설비 가동/비가동 시계열. 시간 무결성 보장, 설비×시간 최적화(UTC).';


 CREATE TABLE `tb_inspection` (
   `inspection_id` bigint NOT NULL AUTO_INCREMENT COMMENT '검사 ID (PK)',
   `work_order_id` varchar(36) DEFAULT NULL COMMENT '검사 대상 작업지시 ID (FK) - 선택',
   `material_lot_id` varchar(36) DEFAULT NULL COMMENT '검사 대상 자재 LOT ID (FK) - 선택',
   `item_id` varchar(36) NOT NULL COMMENT '검사 대상 품목 ID (FK)',
   `inspection_type_code_id` bigint NOT NULL COMMENT '검사 유형 코드 ID (FK→tb_code)',
   `inspection_time` datetime NOT NULL COMMENT '검사 시점 (UTC)',
   `worker_id` varchar(36) NOT NULL COMMENT '검사자 ID (FK→tb_user.user_id)',
   `process_id` varchar(36) DEFAULT NULL COMMENT '검사 공정 ID (FK) - 선택',
   `equipment_id` varchar(36) DEFAULT NULL COMMENT '검사 설비 ID (FK) - 선택',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`inspection_id`),
   KEY `idx_inspection_wo_id` (`work_order_id`),
   KEY `idx_inspection_lot_id` (`material_lot_id`),
   KEY `idx_inspection_item_id` (`item_id`),
   KEY `idx_inspection_type_id` (`inspection_type_code_id`),
   KEY `idx_inspection_time` (`inspection_time`),
   KEY `idx_inspection_process_id` (`process_id`),
   KEY `idx_inspection_equipment_id` (`equipment_id`),
   KEY `idx_insp_worker` (`worker_id`),
   CONSTRAINT `fk_insp_eqp` FOREIGN KEY (`equipment_id`) REFERENCES `tb_equipment` (`equipment_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_insp_item` FOREIGN KEY (`item_id`) REFERENCES `tb_item` (`item_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_insp_lot` FOREIGN KEY (`material_lot_id`) REFERENCES `tb_material_lot` (`material_lot_id`) ON DELETE SET NULL,
   CONSTRAINT `fk_insp_proc` FOREIGN KEY (`process_id`) REFERENCES `tb_process` (`process_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_insp_type` FOREIGN KEY (`inspection_type_code_id`) REFERENCES `tb_code` (`code_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_insp_user` FOREIGN KEY (`worker_id`) REFERENCES `tb_user` (`user_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_insp_wo` FOREIGN KEY (`work_order_id`) REFERENCES `tb_work_order` (`work_order_id`) ON DELETE SET NULL
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='검사: 품목/유형/시간 인덱싱, 작업자=tb_user FK(UTC). 대상(지시/LOT/공정/설비) 선택 FK.';


 CREATE TABLE `tb_inspection_result` (
   `result_id` bigint NOT NULL AUTO_INCREMENT COMMENT '검사 결과 ID (PK)',
   `inspection_id` bigint NOT NULL COMMENT '검사 ID (FK)',
   `item_id` varchar(36) NOT NULL COMMENT '검사 대상 품목 ID (FK)',
   `result_value` varchar(255) NOT NULL COMMENT '측정값(문자열)',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`result_id`),
   UNIQUE KEY `uk_result_insp_item` (`inspection_id`,`item_id`),
   KEY `idx_result_inspection_id` (`inspection_id`),
   KEY `idx_result_item_id` (`item_id`),
   CONSTRAINT `fk_result_inspection` FOREIGN KEY (`inspection_id`) REFERENCES `tb_inspection` (`inspection_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_result_item` FOREIGN KEY (`item_id`) REFERENCES `tb_item` (`item_id`) ON DELETE RESTRICT
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='검사 결과: 동일 검사×품목 1건 보장. 숫자형/판정 컬럼은 선택 확장(UTC).';


 CREATE TABLE `tb_defect` (
   `defect_id` bigint NOT NULL AUTO_INCREMENT COMMENT '불량 ID (PK)',
   `inspection_id` bigint NOT NULL COMMENT '검사 ID (FK)',
   `defect_type_code_id` bigint NOT NULL COMMENT '불량 유형 코드 ID (FK→tb_code)',
   `defect_qty` decimal(10,4) NOT NULL DEFAULT '0.0000' COMMENT '불량 수량(>=0)',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`defect_id`),
   UNIQUE KEY `uk_defect_insp_type` (`inspection_id`,`defect_type_code_id`),
   KEY `idx_defect_inspection_id` (`inspection_id`),
   KEY `idx_defect_type_code_id` (`defect_type_code_id`),
   CONSTRAINT `fk_defect_inspection` FOREIGN KEY (`inspection_id`) REFERENCES `tb_inspection` (`inspection_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_defect_type_code` FOREIGN KEY (`defect_type_code_id`) REFERENCES `tb_code` (`code_id`) ON DELETE RESTRICT,
   CONSTRAINT `ck_defect_qty_nonneg` CHECK ((`defect_qty` >= 0))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='불량: 동일 검사×유형 1건 보장, 수량 비음수 무결성(UTC).';

CREATE TABLE `tb_non_conformance` (
   `non_conformance_id` bigint NOT NULL AUTO_INCREMENT COMMENT '부적합 ID (PK)',
   `defect_id` bigint NOT NULL COMMENT '불량 ID (FK, 1:1)',
   `cause` text COMMENT '부적합 원인',
   `corrective_action` text COMMENT '시정 조치',
   `preventive_action` text COMMENT '예방 조치',
   `report_date` datetime NOT NULL COMMENT '보고 일시 (UTC)',
   `worker_id` varchar(36) NOT NULL COMMENT '보고자/담당자 ID (FK→tb_user.user_id)',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`non_conformance_id`),
   UNIQUE KEY `uk_non_conformance_defect` (`defect_id`),
   KEY `idx_nc_report_date` (`report_date`),
   KEY `idx_nc_worker` (`worker_id`),
   CONSTRAINT `fk_nc_defect` FOREIGN KEY (`defect_id`) REFERENCES `tb_defect` (`defect_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_nc_user` FOREIGN KEY (`worker_id`) REFERENCES `tb_user` (`user_id`) ON DELETE RESTRICT
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='부적합: 불량 1:1 확장. 보고자=tb_user FK, 보고일 조회 최적화(UTC).';

 CREATE TABLE `tb_kpi_target` (
   `target_id` bigint NOT NULL AUTO_INCREMENT COMMENT '목표 ID (PK)',
   `kpi_date` date NOT NULL COMMENT 'KPI 기준 날짜',
   `equipment_id` varchar(36) NOT NULL COMMENT '설비 ID (FK)',
   `process_id` varchar(36) NOT NULL COMMENT '공정 ID (FK)',
   `item_id` varchar(36) NOT NULL COMMENT '품목 ID (FK)',
   `target_oee` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT 'OEE 목표치 (%) [0~100]',
   `target_productivity` decimal(10,4) NOT NULL DEFAULT '0.0000' COMMENT '생산성 목표치 (단위/시간, >=0)',
   `target_yield` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '수율 목표치 (%) [0~100]',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`target_id`),
   UNIQUE KEY `uk_kpi_target_date_eqp_proc_item` (`kpi_date`,`equipment_id`,`process_id`,`item_id`),
   KEY `idx_kpi_target_equipment_id` (`equipment_id`),
   KEY `idx_kpi_target_process_id` (`process_id`),
   KEY `idx_kpi_target_item_id` (`item_id`),
   CONSTRAINT `fk_kpi_target_equipment` FOREIGN KEY (`equipment_id`) REFERENCES `tb_equipment` (`equipment_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_kpi_target_item` FOREIGN KEY (`item_id`) REFERENCES `tb_item` (`item_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_kpi_target_process` FOREIGN KEY (`process_id`) REFERENCES `tb_process` (`process_id`) ON DELETE RESTRICT,
   CONSTRAINT `ck_kpi_oee_range` CHECK ((`target_oee` between 0 and 100)),
   CONSTRAINT `ck_kpi_prod_nonneg` CHECK ((`target_productivity` >= 0)),
   CONSTRAINT `ck_kpi_yield_range` CHECK ((`target_yield` between 0 and 100))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='KPI 목표: 일×설비×공정×품목 축. 퍼센트/음수 가드로 무결성 보장(UTC).';

 CREATE TABLE `tb_audit_log` (
   `log_id` bigint NOT NULL AUTO_INCREMENT COMMENT '로그 ID (PK)',
   `user_id` varchar(36) DEFAULT NULL COMMENT '관련 사용자 ID (tb_user.user_id FK, UUID)',
   `log_type` varchar(50) NOT NULL COMMENT '로그 유형 (예: CREATE, UPDATE, DELETE, LOGIN)',
   `message` text NOT NULL COMMENT '로그 메시지',
   `resource_table` varchar(100) DEFAULT NULL COMMENT '영향 테이블명',
   `resource_id` varchar(255) DEFAULT NULL COMMENT '영향 레코드 ID',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`log_id`),
   KEY `idx_audit_log_user_id` (`user_id`),
   KEY `idx_audit_log_res` (`resource_table`,`resource_id`),
   KEY `idx_audit_created_at` (`created_at`),
   KEY `idx_audit_log_type` (`log_type`),
   CONSTRAINT `fk_audit_user` FOREIGN KEY (`user_id`) REFERENCES `tb_user` (`user_id`) ON DELETE SET NULL,
   CONSTRAINT `ck_audit_is_deleted` CHECK ((`is_deleted` in (0,1)))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='감사 로그: 사용자/리소스/시간 기준 조회 최적화, 사용자 삭제 시 로그 보존(SET NULL, UTC).';


 CREATE TABLE `tb_definition` (
   `definition_id` bigint NOT NULL AUTO_INCREMENT COMMENT '수식 ID (PK)',
   `definition_name` varchar(100) NOT NULL COMMENT '수식 이름 (예: OEE, Yield, Defect Rate)',
   `description` varchar(255) DEFAULT NULL COMMENT '설명',
   `formula` varchar(500) NOT NULL COMMENT '계산 수식 (예: "(good_qty / total_qty) * 100")',
   `parameters` json NOT NULL COMMENT '파라미터 정의 : 사용되는 파라미터 정의 (예: ["good_qty", "total_qty"])',
   `unit` varchar(20) DEFAULT NULL COMMENT '단위 (% , 개, 시간 등)',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`definition_id`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='계산 수식 정의 테이블';


CREATE TABLE `tb_production_log` (
   `log_id` bigint NOT NULL AUTO_INCREMENT COMMENT '생산 로그 ID (PK)',
   `work_order_id` varchar(36) DEFAULT NULL COMMENT '작업 지시 ID (FK)',
   `equipment_id` varchar(36) NOT NULL COMMENT '설비 ID (FK)',
   `process_id` varchar(36) DEFAULT NULL COMMENT '공정 ID (FK)',
   `event_type` bigint NOT NULL COMMENT '이벤트 유형 (FK → tb_code)',
   `event_timestamp` datetime NOT NULL COMMENT '이벤트 발생 시점 (UTC)',
   `event_value` decimal(10,4) NOT NULL DEFAULT '0.0000' COMMENT '이벤트 관련 값 (수량, 시간 등)',
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '레코드 생성 시점 (UTC)',
   PRIMARY KEY (`log_id`),
   UNIQUE KEY `uk_prodlog_unique` (`work_order_id`,`equipment_id`,`process_id`,`event_timestamp`,`event_type`),
   KEY `idx_log_event_time` (`event_timestamp`),
   KEY `idx_log_wo_id` (`work_order_id`),
   KEY `idx_log_eqp_id` (`equipment_id`),
   KEY `fk_prodlog_event_type` (`event_type`),
   CONSTRAINT `fk_prodlog_event_type` FOREIGN KEY (`event_type`) REFERENCES `tb_code` (`code_id`) ON DELETE RESTRICT,
   CONSTRAINT `ck_prodlog_time_order` CHECK ((`event_timestamp` is not null)),
   CONSTRAINT `ck_prodlog_value_nonneg` CHECK ((`event_value` >= 0))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='생산 공정에서 발생하는 원시 이벤트 로그';

 CREATE TABLE `tb_kpi_data` (
   `kpi_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'KPI 기록 ID (PK)',
   `kpi_date` date NOT NULL COMMENT 'KPI 기준 날짜',
   `equipment_id` varchar(36) NOT NULL COMMENT '설비 ID (FK → tb_equipment)',
   `process_id` varchar(36) NOT NULL COMMENT '공정 ID (FK → tb_process)',
   `item_id` varchar(36) NOT NULL COMMENT '품목 ID (FK → tb_item)',
   `work_order_id` varchar(36) DEFAULT NULL COMMENT '지시 ID (FK → tb_workorder)',
   `actual_oee` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '설비 종합 효율 (%) [0~100]',
   `actual_productivity` decimal(10,4) NOT NULL DEFAULT '0.0000' COMMENT '시간당 생산성 (단위/시간)',
   `actual_yield` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '수율 (%) [0~100]',
   `actual_defect_rate` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '불량률 (%) [0~100]',
   `aggregation_type_id` bigint DEFAULT NULL COMMENT '집계 유형 (FK → tb_code.code_id where group_code = "KPI_DATA_TYPE")',
   `batch_group_key` varchar(20) DEFAULT NULL COMMENT '주기적 집계시 중복 체크용',
   `start_time` datetime NOT NULL COMMENT 'KPI 집계 시작 시간',
   `end_time` datetime NOT NULL COMMENT 'KPI 집계 종료 시간',
   `calc_status_code_id` bigint DEFAULT NULL COMMENT '계산 상태 (FK → tb_code.code_id where group_code = "KPI_CALC_STATUS")',
   `calc_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'KPI 계산 시각',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`kpi_id`),
   UNIQUE KEY `uk_kpi_realtime` (`kpi_date`,`work_order_id`,`equipment_id`,`process_id`,`item_id`,`aggregation_type_id`),
   UNIQUE KEY `uk_kpi_daily` (`kpi_date`,`equipment_id`,`process_id`,`item_id`,`batch_group_key`,`aggregation_type_id`),
   KEY `idx_kpi_date` (`kpi_date`),
   KEY `idx_kpi_equipment_id` (`equipment_id`),
   KEY `idx_kpi_process_id` (`process_id`),
   KEY `idx_kpi_item_id` (`item_id`),
   KEY `fk_kpi_work_order` (`work_order_id`),
   KEY `fk_kpi_data_type` (`aggregation_type_id`),
   KEY `fk_kpi_calc_status` (`calc_status_code_id`),
   CONSTRAINT `fk_kpi_calc_status` FOREIGN KEY (`calc_status_code_id`) REFERENCES `tb_code` (`code_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_kpi_data_type` FOREIGN KEY (`aggregation_type_id`) REFERENCES `tb_code` (`code_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_kpi_equipment` FOREIGN KEY (`equipment_id`) REFERENCES `tb_equipment` (`equipment_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_kpi_item` FOREIGN KEY (`item_id`) REFERENCES `tb_item` (`item_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_kpi_process` FOREIGN KEY (`process_id`) REFERENCES `tb_process` (`process_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_kpi_work_order` FOREIGN KEY (`work_order_id`) REFERENCES `tb_work_order` (`work_order_id`) ON DELETE RESTRICT,
   CONSTRAINT `ck_actual_defect_rate_range` CHECK ((`actual_defect_rate` between 0 and 100)),
   CONSTRAINT `ck_actual_oee_range` CHECK ((`actual_oee` between 0 and 100)),
   CONSTRAINT `ck_actual_productivity_nonneg` CHECK ((`actual_productivity` >= 0)),
   CONSTRAINT `ck_actual_yield_range` CHECK ((`actual_yield` between 0 and 100)),
   CONSTRAINT `ck_start_before_end` CHECK ((`end_time` >= `start_time`))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='KPI 데이터: 실시간(퍼포먼스 단위) + 배치(하루 단위) 모두 대응';


 CREATE TABLE `tb_cmms_pm_plan` (
   `plan_id` bigint NOT NULL AUTO_INCREMENT,
   `equipment_id` varchar(36) NOT NULL,
   `task_name` varchar(100) NOT NULL,
   `cycle_type_code_id` bigint NOT NULL,
   `cycle_value` int NOT NULL,
   `last_done_at` datetime DEFAULT NULL,
   `next_due_at` datetime NOT NULL,
   `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
   `is_deleted` tinyint DEFAULT '0',
   `deleted_at` datetime DEFAULT NULL,
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
   `estimated_take_time` int DEFAULT NULL COMMENT '예상 소요 시간(분)',
   PRIMARY KEY (`plan_id`),
   KEY `ix_pm_due` (`next_due_at`),
   KEY `ix_pm_eqp` (`equipment_id`),
   KEY `ix_pm_cycle_type` (`cycle_type_code_id`),
   CONSTRAINT `fk_pm_cycle_typecode` FOREIGN KEY (`cycle_type_code_id`) REFERENCES `tb_code` (`code_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_pm_equipment` FOREIGN KEY (`equipment_id`) REFERENCES `tb_equipment` (`equipment_id`) ON DELETE RESTRICT
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='CMMS: PM 계획(코드마스터)';


 CREATE TABLE `tb_cmms_work_order` (
   `cmms_wo_id` bigint NOT NULL AUTO_INCREMENT,
   `equipment_id` varchar(36) NOT NULL,
   `title` varchar(200) NOT NULL,
   `priority_code_id` bigint NOT NULL,
   `status_code_id` bigint NOT NULL,
   `assignee_user_id` varchar(36) DEFAULT NULL,
   `request_id` varchar(64) DEFAULT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `started_at` datetime DEFAULT NULL,
   `finished_at` datetime DEFAULT NULL,
   `actual_minutes` int DEFAULT NULL,
   `parts_cost` decimal(12,2) DEFAULT NULL,
   `is_deleted` tinyint DEFAULT '0',
   `deleted_at` datetime DEFAULT NULL,
   `created_by` varchar(50) NOT NULL,
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (`cmms_wo_id`),
   UNIQUE KEY `uq_cmms_wo_request_id` (`request_id`),
   KEY `ix_cmms_wo_eqp_created` (`equipment_id`,`created_at`),
   KEY `ix_cmms_wo_status` (`status_code_id`),
   KEY `ix_cmms_wo_priority` (`priority_code_id`),
   KEY `fk_cmms_wo_assignee` (`assignee_user_id`),
   CONSTRAINT `fk_cmms_wo_assignee` FOREIGN KEY (`assignee_user_id`) REFERENCES `tb_user` (`user_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_cmms_wo_equipment` FOREIGN KEY (`equipment_id`) REFERENCES `tb_equipment` (`equipment_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_cmms_wo_priority_code` FOREIGN KEY (`priority_code_id`) REFERENCES `tb_code` (`code_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_cmms_wo_status_code` FOREIGN KEY (`status_code_id`) REFERENCES `tb_code` (`code_id`) ON DELETE RESTRICT
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='CMMS: 보전 작업지시(코드마스터)'  ;


 CREATE TABLE `tb_cmms_work_order_log` (
   `log_id` bigint NOT NULL AUTO_INCREMENT,
   `cmms_wo_id` bigint NOT NULL,
   `from_status_code_id` bigint DEFAULT NULL,
   `to_status_code_id` bigint NOT NULL,
   `changed_by` varchar(36) NOT NULL,
   `changed_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `note` varchar(255) DEFAULT NULL,
   PRIMARY KEY (`log_id`),
   KEY `ix_wolog_wo` (`cmms_wo_id`,`changed_at`),
   KEY `fk_wolog_from_code` (`from_status_code_id`),
   KEY `fk_wolog_to_code` (`to_status_code_id`),
   KEY `fk_cmms_wolog_user` (`changed_by`),
   CONSTRAINT `fk_cmms_wolog_user` FOREIGN KEY (`changed_by`) REFERENCES `tb_user` (`user_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_cmms_wolog_wo` FOREIGN KEY (`cmms_wo_id`) REFERENCES `tb_cmms_work_order` (`cmms_wo_id`) ON DELETE CASCADE,
   CONSTRAINT `fk_wolog_from_code` FOREIGN KEY (`from_status_code_id`) REFERENCES `tb_code` (`code_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_wolog_to_code` FOREIGN KEY (`to_status_code_id`) REFERENCES `tb_code` (`code_id`) ON DELETE RESTRICT
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='CMMS: WO 상태전이 이력(코드마스터)';


 CREATE TABLE `tb_cmms_fault_log` (
   `fault_id` bigint NOT NULL AUTO_INCREMENT,
   `equipment_id` varchar(36) NOT NULL,
   `loss_cat_code_id` bigint NOT NULL,
   `symptom` varchar(255) NOT NULL,
   `action` varchar(255) DEFAULT NULL,
   `occurred_at` datetime NOT NULL,
   `resolved_at` datetime DEFAULT NULL,
   `cmms_wo_id` bigint DEFAULT NULL,
   `is_deleted` tinyint DEFAULT '0',
   `deleted_at` datetime DEFAULT NULL,
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (`fault_id`),
   KEY `ix_fault_time_eqp` (`occurred_at`,`equipment_id`),
   KEY `ix_fault_loss` (`loss_cat_code_id`),
   KEY `fk_fault_equipment` (`equipment_id`),
   KEY `fk_fault_cmmswo` (`cmms_wo_id`),
   CONSTRAINT `fk_fault_cmmswo` FOREIGN KEY (`cmms_wo_id`) REFERENCES `tb_cmms_work_order` (`cmms_wo_id`) ON DELETE SET NULL,
   CONSTRAINT `fk_fault_equipment` FOREIGN KEY (`equipment_id`) REFERENCES `tb_equipment` (`equipment_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_fault_losscode` FOREIGN KEY (`loss_cat_code_id`) REFERENCES `tb_code` (`code_id`) ON DELETE RESTRICT,
   CONSTRAINT `ck_fault_time_order` CHECK (((`resolved_at` is null) or (`resolved_at` >= `occurred_at`)))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='CMMS: 고장/정지 로그(코드마스터)';


 CREATE TABLE `tb_employee` (
   `employee_id` varchar(36) NOT NULL COMMENT '직원 ID (PK, FK→tb_user.user_id)',
   `employee_number` varchar(50) NOT NULL COMMENT '직원 번호',
   `employee_name` varchar(100) NOT NULL COMMENT '직원 이름',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`employee_id`),
   UNIQUE KEY `uk_employee_number` (`employee_number`),
   CONSTRAINT `fk_employee_user` FOREIGN KEY (`employee_id`) REFERENCES `tb_user` (`user_id`) ON DELETE RESTRICT
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='직원 정보: tb_user와 1:1 관계로 직원의 기본 정보를 관리.';


 CREATE TABLE `tb_cert` (
   `cert_id` bigint NOT NULL AUTO_INCREMENT COMMENT '자격증 ID (PK)',
   `cert_code` varchar(50) NOT NULL COMMENT '자격 코드 (유일)',
   `cert_name` varchar(100) NOT NULL COMMENT '자격 명칭',
   `cert_description` varchar(255) DEFAULT NULL COMMENT '설명',
   `cert_valid_period_months` int DEFAULT NULL COMMENT '유효기간 (월 단위, NULL=무기한)',
   `is_deleted` tinyint DEFAULT '0',
   `deleted_at` datetime DEFAULT NULL,
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (`cert_id`),
   UNIQUE KEY `uk_cert_code` (`cert_code`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='자격 마스터: 설비/공정 필요 자격 정의';

 CREATE TABLE `tb_employee_cert` (
   `employee_cert_id` bigint NOT NULL AUTO_INCREMENT COMMENT '직원-자격증 매핑 ID (PK)',
   `employee_id` varchar(36) NOT NULL COMMENT '직원 ID (FK→tb_employee.employee_id)',
   `cert_id` bigint NOT NULL COMMENT '자격증 ID (FK→tb_cert.cert_id)',
   `employee_level_code_id` bigint NOT NULL COMMENT '숙련도 코드 ID (FK→tb_code, 예: BASIC, INTERMEDIATE)',
   `cert_obtained_date` date NOT NULL COMMENT '취득일',
   `cert_expiry_date` date DEFAULT NULL COMMENT '만료일 (NULL=무기한)',
   `is_deleted` tinyint DEFAULT '0',
   `deleted_at` datetime DEFAULT NULL,
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (`employee_cert_id`),
   UNIQUE KEY `uk_employee_cert` (`employee_id`,`cert_id`),
   KEY `fk_employee_cert_cert` (`cert_id`),
   KEY `fk_employee_cert_level` (`employee_level_code_id`),
   CONSTRAINT `fk_employee_cert_cert` FOREIGN KEY (`cert_id`) REFERENCES `tb_cert` (`cert_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_employee_cert_emp` FOREIGN KEY (`employee_id`) REFERENCES `tb_employee` (`employee_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_employee_cert_level` FOREIGN KEY (`employee_level_code_id`) REFERENCES `tb_code` (`code_id`) ON DELETE RESTRICT
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='직원-자격증 매핑: 직원별 자격증/숙련도 관리';

CREATE TABLE `tb_process_cert` (
   `process_cert_id` bigint NOT NULL AUTO_INCREMENT,
   `process_id` varchar(36) NOT NULL COMMENT '공정 ID (FK)',
   `cert_id` bigint NOT NULL COMMENT '자격 ID (FK→tb_cert.cert_id)',
   `is_deleted` tinyint NOT NULL,
   `deleted_at` datetime DEFAULT NULL COMMENT '삭제 일시',
   PRIMARY KEY (`process_cert_id`),
   UNIQUE KEY `uk_proc_cert` (`process_id`,`cert_id`),
   KEY `fk_proc_cert_cert` (`cert_id`),
   CONSTRAINT `fk_proc_cert_cert` FOREIGN KEY (`cert_id`) REFERENCES `tb_cert` (`cert_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_proc_cert_proc` FOREIGN KEY (`process_id`) REFERENCES `tb_process` (`process_id`) ON DELETE RESTRICT
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='공정별 필요 자격 정의';


 CREATE TABLE `tb_equipment_cert` (
   `equipment_cert_id` bigint NOT NULL AUTO_INCREMENT,
   `equipment_id` varchar(36) NOT NULL COMMENT '설비 ID (FK)',
   `cert_id` bigint NOT NULL COMMENT '자격 ID (FK→tb_cert.cert_id)',
   `is_deleted` tinyint NOT NULL,
   `deleted_at` datetime DEFAULT NULL COMMENT '삭제 일시',
   PRIMARY KEY (`equipment_cert_id`),
   UNIQUE KEY `uk_eqp_cert` (`equipment_id`,`cert_id`),
   KEY `fk_eqp_cert_cert` (`cert_id`),
   CONSTRAINT `fk_eqp_cert_cert` FOREIGN KEY (`cert_id`) REFERENCES `tb_cert` (`cert_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_eqp_cert_eqp` FOREIGN KEY (`equipment_id`) REFERENCES `tb_equipment` (`equipment_id`) ON DELETE RESTRICT
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='설비별 필요 자격 정의';

CREATE TABLE `tb_attendance` (
   `id` bigint NOT NULL AUTO_INCREMENT COMMENT '출퇴근 기록 ID (PK)',
   `user_id` varchar(50) NOT NULL COMMENT '직원의 고유 ID',
   `check_time` datetime(6) NOT NULL COMMENT '출, 퇴근 시간 (정밀도 6)',
   `status_code_id` bigint NOT NULL COMMENT '출, 퇴근 상태 (FK)',
   `description` varchar(255) DEFAULT NULL COMMENT '기록에 대한 추가 설명',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`id`),
   KEY `fk_attendance_status_code` (`status_code_id`),
   CONSTRAINT `fk_attendance_status_code` FOREIGN KEY (`status_code_id`) REFERENCES `tb_code` (`code_id`) ON DELETE RESTRICT
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='직원 출퇴근 기록';


 CREATE TABLE `tb_kpi_planned_downtime` (
   `planned_downtime_id` bigint NOT NULL AUTO_INCREMENT COMMENT '계획된 다운타임 ID (PK)',
   `equipment_id` varchar(36) NOT NULL COMMENT '설비 ID (FK)',
   `start_time` timestamp NOT NULL,
   `end_time` timestamp NOT NULL,
   `downtime_type_code_id` bigint NOT NULL COMMENT '다운타임 유형 (예: PM, SHIFT_BREAK, HOLIDAY)',
   `description` varchar(255) DEFAULT NULL COMMENT '상세 설명',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` timestamp NULL DEFAULT NULL,
   `created_by` varchar(50) NOT NULL,
   `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
   `duration_seconds` bigint NOT NULL DEFAULT '0' COMMENT '다운타임 지속 시간(초)',
   PRIMARY KEY (`planned_downtime_id`),
   KEY `idx_equipment_time` (`equipment_id`,`start_time`),
   KEY `fk_downtime_type` (`downtime_type_code_id`),
   CONSTRAINT `fk_downtime_equipment` FOREIGN KEY (`equipment_id`) REFERENCES `tb_equipment` (`equipment_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_downtime_type` FOREIGN KEY (`downtime_type_code_id`) REFERENCES `tb_code` (`code_id`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='계획된 다운타임 기록';



