
CREATE TABLE `tb_role` (
   `role_id` bigint NOT NULL AUTO_INCREMENT COMMENT '역할 ID (PK)',
   `role_code` varchar(50) NOT NULL COMMENT '역할 코드 (전역 유일) 예: ROLE_OP, ROLE_QA, ROLE_ADMIN',
   `role_name` varchar(100) NOT NULL COMMENT '역할 명칭',
   `description` varchar(255) DEFAULT NULL COMMENT '설명',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`role_id`),
   UNIQUE KEY `uk_role_code` (`role_code`),
   CONSTRAINT `ck_role_is_deleted` CHECK ((`is_deleted` in (0,1)))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='역할 마스터: 인가 레벨 정의. ROLE_OP/QA/ADMIN 기본 시드 권장(UTC).';

CREATE TABLE `tb_user` (
   `user_id` varchar(36) NOT NULL COMMENT '사용자 ID (UUID, PK)',
   `username` varchar(50) NOT NULL COMMENT '로그인 ID (유일, 소문자 권장)',
   `email` varchar(255) DEFAULT NULL COMMENT '이메일(선택, 유일 권장)',
   `password_hash` varchar(100) NOT NULL COMMENT '비밀번호 해시(예: BCrypt 60자, Argon2id 가능)',
   `password_algo` varchar(20) NOT NULL DEFAULT 'bcrypt' COMMENT '해시 알고리즘(bcrypt/argon2id)',
   `is_active` tinyint NOT NULL DEFAULT '1' COMMENT '활성 여부(1/0)',
   `failed_login_count` int NOT NULL DEFAULT '0' COMMENT '연속 실패 횟수(>=0)',
   `locked_until` datetime DEFAULT NULL COMMENT '잠금 해제 예정 시각(UTC)',
   `last_login_at` datetime DEFAULT NULL COMMENT '마지막 로그인 시각(UTC)',
   `phone` varchar(30) DEFAULT NULL COMMENT '연락처(선택)',
   `display_name` varchar(100) DEFAULT NULL COMMENT '표시명(선택)',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`user_id`),
   UNIQUE KEY `uk_user_username` (`username`),
   UNIQUE KEY `uk_user_email` (`email`),
   CONSTRAINT `ck_user_failed_cnt` CHECK ((`failed_login_count` >= 0)),
   CONSTRAINT `ck_user_is_active` CHECK ((`is_active` in (0,1))),
   CONSTRAINT `ck_user_is_deleted` CHECK ((`is_deleted` in (0,1)))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자 마스터: 로그인/상태/보안 메타. 해시는 필수, 평문 금지(UTC).';

CREATE TABLE `tb_user_role` (
   `user_role_id` bigint NOT NULL AUTO_INCREMENT COMMENT '사용자-역할 매핑 ID (PK)',
   `user_id` varchar(36) NOT NULL COMMENT '사용자 ID (FK)',
   `role_id` bigint NOT NULL COMMENT '역할 ID (FK)',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제 플래그(0/1)',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`user_role_id`),
   UNIQUE KEY `uk_user_role` (`user_id`,`role_id`),
   KEY `idx_userrole_user` (`user_id`),
   KEY `idx_userrole_role` (`role_id`),
   CONSTRAINT `fk_userrole_role` FOREIGN KEY (`role_id`) REFERENCES `tb_role` (`role_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_userrole_user` FOREIGN KEY (`user_id`) REFERENCES `tb_user` (`user_id`) ON DELETE RESTRICT,
   CONSTRAINT `ck_userrole_is_deleted` CHECK ((`is_deleted` in (0,1)))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자-역할 매핑(보수형): FK 삭제 RESTRICT, 중복 배정 방지(UTC).';

CREATE TABLE `tb_role_menu` (
   `role_menu_id` bigint NOT NULL AUTO_INCREMENT COMMENT '역할-메뉴 매핑 ID (PK)',
   `role_id` bigint NOT NULL COMMENT '역할 ID (FK)',
   `menu_id` bigint NOT NULL COMMENT '메뉴 ID (FK)',
   `allow_read` tinyint NOT NULL DEFAULT '1' COMMENT '읽기 허용(0/1)',
   `allow_write` tinyint NOT NULL DEFAULT '0' COMMENT '쓰기 허용(0/1)',
   `allow_exec` tinyint NOT NULL DEFAULT '0' COMMENT '실행 허용(0/1)',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제(0/1)',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`role_menu_id`),
   UNIQUE KEY `uk_role_menu` (`role_id`,`menu_id`),
   KEY `idx_rm_role` (`role_id`),
   KEY `idx_rm_menu` (`menu_id`),
   CONSTRAINT `fk_rm_menu` FOREIGN KEY (`menu_id`) REFERENCES `tb_menu` (`menu_id`) ON DELETE RESTRICT,
   CONSTRAINT `fk_rm_role` FOREIGN KEY (`role_id`) REFERENCES `tb_role` (`role_id`) ON DELETE RESTRICT,
   CONSTRAINT `ck_rm_flags` CHECK (((`allow_read` in (0,1)) and (`allow_write` in (0,1)) and (`allow_exec` in (0,1)) and (`is_deleted` in (0,1))))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='역할-메뉴 매핑(보수형): FK 삭제 RESTRICT, 플래그 무결성(UTC).';

CREATE TABLE `tb_menu` (
   `menu_id` bigint NOT NULL AUTO_INCREMENT COMMENT '메뉴 ID (PK)',
   `parent_id` bigint DEFAULT NULL COMMENT '부모 메뉴 ID (Self FK, 최상위 NULL)',
   `menu_code` varchar(100) NOT NULL COMMENT '메뉴 코드(전역 유일) 예: DASHBOARD, PROD_RESULT',
   `menu_name` varchar(150) NOT NULL COMMENT '메뉴 표시명',
   `path` varchar(255) NOT NULL COMMENT '라우트/URL 경로 예: /dashboard',
   `component` varchar(255) DEFAULT NULL COMMENT '프론트 컴포넌트 키(선택)',
   `icon` varchar(100) DEFAULT NULL COMMENT '아이콘 키(선택)',
   `sort_order` int NOT NULL DEFAULT '0' COMMENT '정렬 순서',
   `is_public` tinyint NOT NULL DEFAULT '0' COMMENT '비로그인 접근(0/1)',
   `is_active` tinyint NOT NULL DEFAULT '1' COMMENT '활성(0/1)',
   `is_deleted` tinyint DEFAULT '0' COMMENT '소프트삭제(0/1)',
   `deleted_at` datetime DEFAULT NULL COMMENT 'UTC',
   `created_by` varchar(50) NOT NULL,
   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
   `modified_by` varchar(50) DEFAULT NULL,
   `modified_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC',
   PRIMARY KEY (`menu_id`),
   UNIQUE KEY `uk_menu_code` (`menu_code`),
   KEY `idx_menu_parent` (`parent_id`),
   KEY `idx_menu_path` (`path`),
   KEY `idx_menu_sort` (`sort_order`),
   KEY `idx_menu_parent_sort` (`parent_id`,`sort_order`),
   CONSTRAINT `fk_menu_parent` FOREIGN KEY (`parent_id`) REFERENCES `tb_menu` (`menu_id`) ON DELETE RESTRICT,
   CONSTRAINT `ck_menu_flags` CHECK (((`is_public` in (0,1)) and (`is_active` in (0,1)) and (`is_deleted` in (0,1))))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='메뉴 마스터(보수형): 부모 삭제 전 자식 정리 필요, 트리/정렬 인덱스 강화(UTC).';
